#!/usr/bin/env python3
"""Advantage figure: (a) final FoM, ours vs GCN-RL vs BO, per circuit;
(b) budget friendliness: evaluations for ours to reach GCN-RL's final FoM."""
import json, glob, os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

RES = os.path.join(os.path.dirname(__file__), "..", "results")
BLUE, AQUA, YELLOW = "#2a78d6", "#1baf7a", "#eda100"
INK, MUT, GRID = "#0b0b0b", "#898781", "#e1e0d9"
plt.rcParams.update({
    "font.size": 8.5, "font.family": "DejaVu Sans",
    "axes.edgecolor": "#c3c2b7", "axes.labelcolor": INK,
    "xtick.color": "#52514e", "ytick.color": "#52514e", "axes.grid": True,
    "grid.color": GRID, "grid.linewidth": 0.5, "axes.axisbelow": True,
    "legend.frameon": False})

def runs(m, ct):
    out = []
    for f in glob.glob(os.path.join(RES, f"{m}_{ct}_gf180_s*.json")):
        r = json.load(open(f))
        if r["budget"] == 600 and not r.get("loaded"):
            out.append(r)
    return out

def stat(m, ct):
    v = [r["best_fom"] for r in runs(m, ct)]
    return np.mean(v), np.std(v)

CTS = ["CT1", "CT2", "CT3"]
NICE = ["CT-1", "CT-2", "CT-3"]

fig, (a1, a2) = plt.subplots(1, 2, figsize=(7.05, 2.35),
                             gridspec_kw={"width_ratios": [1.15, 1.0]},
                             constrained_layout=True)

# ---- (a) final FoM dot plot ----
methods = [("gcnsac_tskf_pia_ekv", "Ours (PIA-EKV)", BLUE),
           ("gcnddpg", "GCN-RL (GCN+DDPG)", AQUA),
           ("bo", "BO (best classical)", YELLOW)]
x = np.arange(3)
off = {-1: -0.22, 0: 0.0, 1: 0.22}
for k, (m, lbl, col) in enumerate(methods):
    mus, sds = zip(*[stat(m, ct) for ct in CTS])
    xs = x + off[k - 1]
    a1.errorbar(xs, mus, yerr=sds, fmt="o", color=col, ms=6.5,
                capsize=3, lw=1.4, label=lbl,
                markeredgecolor="white", markeredgewidth=0.8)
# value labels: one small column per circuit, right of the group,
# stacked vertically in method order so no text touches markers or bars
allmu = {m: [stat(m, ct)[0] for ct in CTS] for m, _, _ in methods}
for ci in range(3):
    base = np.mean([allmu[m][ci] for m, _, _ in methods])
    for k, (m, lbl, col) in enumerate(methods):
        a1.text(ci + 0.36, base + (1 - k) * 0.115, f"{allmu[m][ci]:.2f}",
                ha="left", va="center", fontsize=6.4, color=col)
a1.set_xticks(x, NICE)
a1.set_xlim(-0.55, 2.72)
a1.set_ylabel("final unified FoM (5 seeds)")
a1.set_title("(a) Final quality at 600 evaluations", fontsize=8.7)
a1.legend(fontsize=6.8, loc="lower left", handletextpad=0.2)
a1.set_ylim(2.9, 4.15)

# ---- (b) evaluations for ours to reach GCN-RL's final FoM ----
need = []
for ct in CTS:
    tgt = np.mean([r["history"][-1][1] for r in runs("gcnddpg", ct)])
    hits = []
    for r in runs("gcnsac_tskf_pia_ekv", ct):
        hit = next((s for s, b in r["history"] if b >= tgt), None)
        hits.append(hit if hit else 600)
    need.append(np.mean(hits))

y = np.arange(3)
a2.barh(y + 0.19, [600] * 3, height=0.34, color=AQUA, alpha=0.85,
        label="GCN-RL budget")
a2.barh(y - 0.19, need, height=0.34, color=BLUE, label="Ours, to same FoM")
for yi, n in zip(y, need):
    a2.annotate(f"{n:.0f}  ({600/n:.1f}$\\times$ fewer)",
                (n + 12, yi - 0.19), va="center", fontsize=7.2, color=BLUE,
                weight="bold")
a2.set_yticks(y, NICE)
a2.invert_yaxis()
a2.set_xlim(0, 780)
a2.set_xlabel("simulator evaluations")
a2.set_title("(b) Budget to reach GCN-RL's final FoM", fontsize=8.7)
a2.legend(fontsize=6.8, loc="upper center", ncol=2,
          bbox_to_anchor=(0.5, -0.28), handletextpad=0.35)


fig.savefig(os.path.join(RES, "figs", "F_advantage.pdf"), bbox_inches="tight")
plt.close(fig)
# macros for the manuscript text
PAP = os.path.expanduser("~/work/paper")
with open(os.path.join(PAP, "adv_macros.tex"), "w") as fh:
    fh.write("% auto-generated by fig_advantage.py\n")
    fh.write("\\newcommand{\\AdvNeedA}{%d}\n" % round(need[0]))
    fh.write("\\newcommand{\\AdvNeedB}{%d}\n" % round(need[1]))
    fh.write("\\newcommand{\\AdvNeedC}{%d}\n" % round(need[2]))
    fh.write("\\newcommand{\\AdvSpeedMax}{%.1f}\n" % (600 / min(need)))
    fh.write("\\newcommand{\\AdvSpeedMin}{%.1f}\n" % (600 / max(need)))
print("advantage figure + macros done:", [round(n) for n in need])
